#!/bin/zsh

function ninit(){
text="$(xsel -o)"
info=("${(f)$($binary info)}")
uri="$info[1]"

[[ -z "$uri" ]] && zenity --timeout 5 --info --text "Unable to obtain uri information. Retry" && exit 1
domain="$(awk -F/ '{print $3 }' <<< $uri)"

filename="$(cut -d '|' -f 1 <<< $info[2] | tr -s ' ' | tr ' ' '-' | tr -dc '[[:alnum:]]\-.')"
fullpath="${noteroot}$domain/"

filename="${fullpath}${filename}"
}

matches(){
IFS=$'\0'
cp $(/bin/grep -ilZr $1 $noteroot) /tmp/$$/
}
noteroot="$HOME/Documents/notes/fnotes/"
binary="$HOME/bin/fxr"


if [[ -z $1 ||  $1 =~ a.* ]];then
    ninit || return 1
    [[ ! -d $fullpath ]] && mkdir -p $fullpath
    #while :;do
        #temp="${filename}.${RANDOM}"
        #[[ -f "$temp" ]] && continue
        #filename="$temp"
        #break
    #done
    if [[ -f "$filename.data" ]];then 
        if [[ "$(grep URI $filename.data | cut -d ":" -f 2)" == "$uri" ]];then
 
        else          #False positive
            touch $filename.{data,html}
            $binary save ${filename}.html || exit 1
        fi
    else
        touch $filename.{data,html}
        $binary save ${filename}.html || exit 1
    fi
    echo -e "\n\n=================================`date +%F`=========================" >> "${filename}.data" || exit 1
    echo "URI:$info[1]" >> "${filename}.data" || exit 1
    echo "TITLE: $info[2]" >> "${filename}.data" || exit 1
    echo "$text" >> "${filename}.data" || exit 1
    echo -e "====================================End Of note============================\n\n" >> "${filename}.data" || exit 1
    ~/bin/booktwit $uri "$info" &
    #notify-send -u critical "$uri successfully added!"
    echo "${filename}.data"

elif [[ $1 =~ r.* ]];then
     ninit || return 1
     $BROWSER $filename.html &>/dev/null &
     cat $filename.data |  zenity --text-info --height 400 --width 900 

elif [[ $1 =~ e.* ]];then 
    tags=($(zenity  --title "Enter" --entry --text "Enter the tags"))
    [[ -z $tags ]] && exit 1
    zmodload zsh/files
    mkdir -p /tmp/$$/
    for t in $tags;do
        matches $t 
    done
    dir="/tmp/$$/*.data"
    file=$(zenity --list --title "Search Results" --text "Search results" --column "Files" $dir)
    while [[ ! -z $file ]];do
        cat $file | zenity --text-info --height 400 --width 900
        #zenity --question --text "Satisified ?" || break
        file=$(zenity --list --title "Search Results" --text "Search results" --column "Files" $dir)
    done
else
    notify-send -u critical "Invalid function"
    exit 1
fi

