#!/bin/zsh
set -x
matches(){
IFS=$'\0'
cp $(/bin/grep -ilZr $1 $noteroot) /tmp/$$/

}


action="$1"
shift

if [[ $action =~ a.* ]];then
    grabber="scrot"
    pidof X &>/dev/null || grabber="fbgrab"
    domain="${1%%:*}"
    noteroot="$HOME/Documents/notes/gnotes/${domain}"
    [[ ! -d $noteroot ]] && mkdir -p $noteroot
    text="$(xsel -o)"
    pid=${1##*:}
    file="${1// /-}"
    pngfile="$noteroot/$file.png"
    echo -e "\n\n=================================$(date +%F)=========================" >> "$noteroot/${file}.data"
    echo "TITLE: $1" >> $noteroot/$file.data
    echo "COMMAND: $(cat /proc/$pid/cmdline | tr '\0' ':')" >> $noteroot/$file.data
    echo "$text" >> $noteroot/$file.data
    if [[ -f $pngfie ]];then pngfile="$noteroot/$file.$RANDOM.png";fi
    $grabber $pngfile
    echo "$noteroot/$file.data"
    exit 0
elif [[ $action =~ r.* ]];then
     echo "Retrieval not implemented yet"
     exit 1
elif [[ $action =~ e.* ]];then
    tags=($(zenity  --title "Enter" --entry --text "Enter the tags"))
    [[ -z $tags ]] && exit 1
    zmodload zsh/files
    mkdir -p /tmp/$$/
    for t in $tags;do
        matches $t
    done
    dir="/tmp/$$/*.data"
    file=$(zenity --list --title "Search Results" --text "Search results" --column "Files" $dir)
    while [[ ! -z $file ]];do
        cat $file | zenity --text-info --height 400 --width 900
        #zenity --question --text "Satisified ?" || break
        file=$(zenity --list --title "Search Results" --text "Search results" --column "Files" $dir)
    done
    feh /tmp/$$/*.png
    exit 0
else
    echo "Fucked up!"
    exit 1
fi
set +x
