setopt no_global_rcs
#{{{
#fpath=( ~/.zsh/func /usr/share/zsh/site-functions /usr/share/zsh/4.3.10/functions/Calendar /usr/share/zsh/4.3.10/functions/Completion /usr/share/zsh/4.3.10/functions/Completion/AIX /usr/share/zsh/4.3.10/functions/Completion/Base /usr/share/zsh/4.3.10/functions/Completion/BSD /usr/share/zsh/4.3.10/functions/Completion/Cygwin /usr/share/zsh/4.3.10/functions/Completion/Darwin /usr/share/zsh/4.3.10/functions/Completion/Debian /usr/share/zsh/4.3.10/functions/Completion/Linux /usr/share/zsh/4.3.10/functions/Completion/Mandriva /usr/share/zsh/4.3.10/functions/Completion/Redhat /usr/share/zsh/4.3.10/functions/Completion/Solaris /usr/share/zsh/4.3.10/functions/Completion/Unix /usr/share/zsh/4.3.10/functions/Completion/X /usr/share/zsh/4.3.10/functions/Completion/Zsh /usr/share/zsh/4.3.10/functions/Exceptions /usr/share/zsh/4.3.10/functions/MIME /usr/share/zsh/4.3.10/functions/Misc /usr/share/zsh/4.3.10/functions/Newuser /usr/share/zsh/4.3.10/functions/Prompts /usr/share/zsh/4.3.10/functions/TCP /usr/share/zsh/4.3.10/functions/VCS_Info /usr/share/zsh/4.3.10/functions/VCS_Info/Backends /usr/share/zsh/4.3.10/functions/Zftp /usr/share/zsh/4.3.10/functions/Zle)

#fpath=( ~/.zsh/func /usr/share/zsh/4.3.10/functions/Completion /usr/share/zsh/4.3.10/functions/Completion/Base /usr/share/zsh/4.3.10/functions/Completion/Linux  /usr/share/zsh/4.3.10/functions/Completion/X /usr/share/zsh/4.3.10/functions/Completion/Unix /usr/share/zsh/4.3.10/functions/Completion/Zsh /usr/share/zsh/4.3.10/functions/Exceptions /usr/share/zsh/4.3.10/functions/MIME /usr/share/zsh/4.3.10/functions/Misc /usr/share/zsh/4.3.10/functions/Newuser /usr/share/zsh/4.3.10/functions/Prompts /usr/share/zsh/4.3.10/functions/TCP /usr/share/zsh/4.3.10/functions/Zle)

#fpath=( ~/.zsh/func /usr/share/zsh/4.3.10/functions/Completion /usr/share/zsh/4.3.10/functions/Completion/Base /usr/share/zsh/4.3.10/functions/Completion/Linux  /usr/share/zsh/4.3.10/functions/Completion/Unix /usr/share/zsh/4.3.10/functions/Completion/Zsh /usr/share/zsh/4.3.10/functions/Misc /usr/share/zsh/4.3.10/functions/Zle)
#}}}
#fpath=( ~/.zsh/func /usr/share/zsh/4.3.10/functions/Completion /usr/share/zsh/4.3.10/functions/Completion/Base /usr/share/zsh/4.3.10/functions/Completion/Unix /usr/share/zsh/4.3.10/functions/Completion/Zsh /usr/share/zsh/4.3.10/functions/Misc /usr/share/zsh/4.3.10/functions/Zle)
fpath=( ~/.zsh/func/Unix ~/.zsh/func/Linux /usr/share/zsh/4.3.10/functions/Completion /usr/share/zsh/4.3.10/functions/Completion/Base /usr/share/zsh/4.3.10/functions/Completion/Zsh /usr/share/zsh/4.3.10/functions/Misc /usr/share/zsh/4.3.10/functions/Zle)
