#!/bin/bash
set -x
echo "Load modules kvm and kvm_amd"
echo "sudo modprobe kvm"
echo "sudo modprobe kvm_amd"
read

~/bin/ssh_expect
#-usb -usbdevice host:1d6b:0001
echo "All done; use alias archie to login if required"
$LOCK/qemu qemu-system-x86_64 -name Archie -enable-kvm  -monitor telnet:127.0.0.1:6666,server,nowait -m 1024 -hda /media/Sentinel/Arch64.qcow -net nic,model=virtio,vlan=1 -net user,vlan=1 -redir tcp:2222::22  -daemonize

echo 1 > /sys/kernel/mm/ksm/run
sleep 5
$LOCK/sshfs sshfs -p 2222 raghu@localhost:/home/raghu /media/Archie
set +x
