#!/bin/bash
# set ft=sh

pronounce(){ 
if [[ ! -f $XDG_CACHE_HOME/pronounce/$1 ]];then 
    wget -qO- $(wget -qO- "http://dictionary.reference.com/browse/$@" | grep 'soundUrl' | head -n 1 | sed 's|.*soundUrl=\([^&]*\)&.*|\1|' | sed 's/%3A/:/g;s/%2F/\//g') | tee $XDG_CACHE_HOME/pronounce/$1 |  /usr/bin/mplayer -really-quiet -cache 8192 -  
else
    mplayer $XDG_CACHE_HOME/pronounce/$1
fi
}

function translate(){
wget -qO - "http://ajax.googleapis.com/ajax/services/language/translate?langpair=|en&v=1.0&q=`xsel`" |cut -d \" -f 6
}

pacfilter(){
#set -x
client="yaourt"
case $1 in
*ti*)
$client -Ss $2 | /bin/grep -A 1 --color -E ".*/.*$2.*(\)|\])$"
;;
*tx*)
$client -Ss $2 |  /bin/grep -B 1 --color -E  '.*$2.*[^0-9]+.*'
;;
esac
#set +x
}

map(){
    local command i rep
    if [ $# -lt 2 ] || [[ ! "$@" =~ :[[:space:]] ]];then
        echo "Invalid syntax." >&2; return 1
    fi
    until [[ $1 =~ : ]]; do
        command="$command $1"; shift
    done
    command="$command ${1%:}"; shift
    for i in "$@"; do
        if [[ $command =~ \{\} ]];then
            rep="${command//\{\}/\"$i\"}"
            eval "${rep//\\/\\\\}"
        else
            eval "${command//\\/\\\\} \"${i//\\/\\\\}\""
        fi
    done
}

function clik(){
sleep 5
scrot
notify-send "Done!"
ls *.png
}

function mpl() 
{
$HOME/bin/mplayer "$@"
}

function mutt()
{
mount | grep -q wormole || echo "CRITICAL: The rc directory is not mounted"
LD_PRELOAD=/usr/lib/libtcmalloc_minimal.so  /usr/bin/mutt 
}

function download(){
histfile="$HOME/.download_history"

if [[ "$@" =~ .*torrent$ ]];then

    pidof -s rtorrent  &>/dev/null || ~/bin/torrent

    [[ $1 =~ ^http.* ]] && wget -q $1 > ~/.rtorrent/watch/${1##*/} && echo "$@ ============ $(aria2c -S ~/.rtorrent/watch/${1##*/})===========$(date)" >> $histfile && exit

    cp "$@" ~/.rtorrent/watch/
    echo "$@ ============ $(aria2c -S $@ | grep Name) ====================$(date)" >> $histfile
    mv "$@" ~/.torrents/

else

    gid=$(aria2rpc addUri "$@")
    echo "$gid:$@ =============== $(date)" >> $histfile 
    #aria2rpc tellStatus gid
fi
}

function pkgsearch(){
#set -x
if [[ $#  < 1 ]];then
    echo "pkgsearch term pkglist"
    return 1
fi
term="$1"
shift
pkg="$@"
for i in $pkg
do
 for j in `pacman -Ql $i | cut -d " " -f 2`
 do
	grep -l -i $term $j
 done
done
#set +x
}

function getmovie (){

    /usr/bin/get_movie.py `/usr/bin/search_movie.py "$@" | head -3  | tail -1 | cut -d ":" -f 2`

}
function man2pdf(){ 
man -t ${1:?Specify man as arg} | ps2pdf -dCompatibility=1.3 - - > ${1}.pdf 
}

function vim(){
if [[ ! -f "$@" ]];then echo "File not found";return 1;fi
LD_PRELOAD=/usr/lib/libjemalloc.so /usr/bin/vim "$@"
}

function cnkt(){
TERM=xterm
#ssh -D 1080 rprabhu@proxy.eglbp.corp.yahoo.com 
#-L 6891:socks.yahoo.com:1080
ssh rprabhu@proxy.eglbp.corp.yahoo.com -L 1080:socks.yahoo.com:1080
}

function randbash(){
curl -s http://bash.org/?random1|grep -oE "<p class=\"quote\">.*</p>.*</p>"|grep -oE "<p class=\"qt.*?</p>"|sed -e 's/<\/p>/\n/g' -e 's/<p class=\"qt\">//g' -e 's/<p class=\"qt\">//g'|perl -ne 'use HTML::Entities;print decode_entities($_),"\n"'| head -1  
#awk 'length($0)>0 {printf( $0 "\n%%\n" )}' > ~/bash_quotes.txt
}


function ifind(){
find . -iname "*$@*"
}

mountole(){
#sudo sed -i -e '/.*ecryptfs.*/s|^#\(.*\)$|\1|g' /etc/fstab 1>/dev/null
keyctl list @u | grep -q e90  || ecryptfs-add-passphrase #&>/dev/null
keyctl list @u | grep -q e90 && mount -i /home/raghavendra/wormole
#sudo sed -i -e '/.*ecryptfs.*/s|^/\(.*\)$|#&|g' /etc/fstab 1>/dev/null  
[[ $? = "0" ]] && echo "Done!"
}


geoip () { curl -s "http://www.geoiptool.com/?IP=$1" | html2text | egrep --color 'City:|IP Address:|Country:'; }

bbcradio() { local s;echo "Select a station:";select s in 1 1x 2 3 4 5 6 7 "Asian Network an" "Nations & Local lcl";do break;done;s=($s);/usr/bin/mplayer -playlist "http://www.bbc.co.uk/radio/listen/live/r"${s[@]: -1}".asx";}


function pactest(){
	sourcefile="/home/raghavendra/config/pacman.conf.testing"
	if [[ $1 = "kmod" ]];then sourcefile=/home/raghavendra/config/pacman.conf.kdemod;elif [[ $1 = "non" ]];then sourcefile=/home/raghavendra/config/pacman.conf.nonstandard;elif [[ $1 = "rollback" ]];then sourcefile=/home/raghavendra/config/pacman.conf.rollback;fi
	shift
	sudo cp -v $sourcefile /etc/pacman.conf
	sudo pacman -q -Sy
	sudo pacman -Ss "$@"
	read
	sudo cp -v /home/raghavendra/config/pacman.conf.standard /etc/pacman.conf
	sudo pacman -q -Sy 1>/dev/null
}

function flushmac(){
rm -rf /home/raghavendra/.macromedia/Flash_Player/*;
mkdir -p ~/.macromedia/Flash_Player/macromedia.com/support/flashplayer/sys
cp ~/Arch/settings.sol ~/.macromedia/Flash_Player/macromedia.com/support/flashplayer/sys/
}

function def(){
 
 wn $1 -over
 if [ $? != "0" ];then echo $1 >> ~/wordlist;fi               
}

function disappear(){
sudo /etc/rc.d/tor start
sudo /etc/rc.d/privoxy start
}

function igrep(){
FILENAME=$1
PATTERN=$2
find . -iname "$FILENAME" -exec grep -il "$PATTERN" {} \;
}

function lookup(){
links -dump http://wordnet.princeton.edu/perl/webwn?s=$1 | grep -i --word-regexp --color=always -B 2 -A 5 $1 | sed '$d'
}

function checkup() { curl -s dict://dict.org/d:"$@" | tail +4; }

function stemp() { 
echo `acpi -t | awk -F ',' '{ print $2 }' | cut -d " " -f 2`
echo `nvidia-settings -q gpucoretemp | grep Supernova | cut -d ":" -f 3`
#echo `sudo hddtemp SATA:/dev/sda | cut -d ":" -f 3`;
 }

function clifu(){
wget -O - "http://www.commandlinefu.com/commands/browse/rss" 2>/dev/null | awk '/\s*<title/ {z=match($0, /CDATA\[([^\]]*)\]/, b);print b[1]} /\s*<description/ {c=match($0, /code>(.*)<\/code>/, d);print d[1]"\n"} '
}


function ncm(){
#if [ ! -f /var/run/daemons/mpd ];then sudo /etc/rc.d/mpd start;fi
ncmpcpp
}


function rcstart(){
for d in $@;do
    if [[ -f /var/run/daemons/$d ]];then
        sudo /etc/rc.d/$d stop; sleep 2; sudo /etc/rc.d/$d start
    else
        sudo /etc/rc.d/$d start
    fi
done
}

function cscore()
{
    curl -s -e "http://www.google.com" -A "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.1) Gecko/20061204 Firefox/2.0.0.1" "http://livechat.rediff.com:80/sports/score/score.txt"
}

function whichpack(){
pacman -Q | grep "$@"
}

function max(){
~/bin/mplayeraux "$@"
}

function rsize() {
wget --spider "$@" -o /tmp/wget_tmp; grep -i Length /tmp/wget_tmp; rm /tmp/wget_tmp
}

function buildabs()
{
    ABDIR="/var/abs/" 
    abpath=$(find -O3 /var/abs/ -maxdepth 2 -name "$@" -type d | head -1)
    cp -Rv $abpath /dev/shm/
    cd /dev/shm/$1
    #clear
}   

function vpdf(){
pdftohtml -q -stdout -noframes "$@" | w3m -T text/html
}

function view()
{
if [[ -z "$@" ]];then
    thunar ~/Documents
elif [[ $1 =~ ^http:.* ]];then
    url=${1#*=}   # for urls like http://docs.google.com/viewer?url=<pdfurl>
    dest="$HOME/Documents/${1##*/}"
    wget -O - -q $url > $dest
    detach $VIEWER $dest
else
    detach $VIEWER "$@" 
fi
}

function rcstop(){
for d in $@;do
    sudo /etc/rc.d/$d stop
done
}


function whoru() { echo "Path:"`which $@`; which $1 |  xargs -i pacman -Qo {} ; }

function fdz() { ls -lth |  egrep "[0-9](M|G)" | sort -k 5 -n | cut -d " " -f 5,6-; }

function dz() { find . -maxdepth $1 -type d -exec du {} \; | sort -n | awk '{ print $2,"\t",$1/1024,"MB" }' | uniq; }
function psp() { ps auxww | /bin/grep -i "$@"; }
function svim() { LD_PRELOAD=/usr/lib/libjemalloc.so sudo vim "$@";}
function bkp() 
{   
    rstr=`date +%s`; dest=~/Backup/`basename "$@"`.$rstr
    cp "$@" $dest; echo "Enter description"; read desc
    if [ -n "${desc}" ]
    then
       echo "$@: "`date`    >> ~/Backup/bjournal
       echo "----------------------------------------" >> ~/Backup/bjournal
       echo "Backup filename: "`basename $dest` >>  ~/Backup/bjournal
       echo "Description:" >>  ~/Backup/bjournal
       echo $desc >> ~/Backup/bjournal
       echo " " >> ~/Backup/bjournal
    fi
}


function mpd_album(){
	rm -f ~/Albums/*
	avatar-factory --icon-size 60 --name 2 -g music /home/raghavendra/mpd/music ~/Albums
}

function get_rss(){
	rsstail -u http://rss.slashdot.org/Slashdot/slashdot -u http://www.reddit.com/.rss
}

function newcnd() { echo "$@" >> ~/newcomies; }

function restorrent(){ 
screen -c /home/raghavendra/.rtorrent/.screenrc -r torrent;
}

calc() {
  echo "scale=5; $@" | bc
}

define() {
  local LNG=$(echo $LANG | cut -d '_' -f 1)
  local CHARSET=$(echo $LANG | cut -d '.' -f 2)
  lynx -accept_all_cookies -dump -hiddenlinks=ignore -nonumbers -assume_charset="$CHARSET" -display_charset="$CHARSET" "http://www.google.com/search?hl=${LNG}&q=define%3A+${1}&btnG=Google+Search" | grep -m 5 -C 2 -A 5 -w "*" > /tmp/define
  if [ ! -s /tmp/define ]; then
    echo "Sorry, google doesn't know this one..."
    rm -f /tmp/define
    return 1
  else
      mecho "$(cat /tmp/define | grep -v Search)"
    echo ""
  fi
  rm -f /tmp/define
  echo $1 >> ~/wordlist
  return 0
}


function myip(){
upnpc -s | grep External | cut -d "=" -f 2
}


function lowmode(){
echo "This will kill many daemons ..... "
read
for daemon in `cat ~/.daemons`
do
    sudo /etc/rc.d/$daemon stop
done

echo "This will unmount many drives..........."
read
~/bin/unmount-removables
sudo umount /media/System /media/Sentinel /media/Colossus /media/Vanguard /home/raghavendra/wormole /var/lib/pacman.db /proc/bus/usb

echo "Backlight to zero"
echo 0 > /sys/devices/virtual/backlight/acpi_video0/brightness
echo "Remove usb cables and start atd if needed"
}

function highmode(){
echo "This will start many daemons ..... "
read
for daemon in `cat .daemons`
do
    sudo /etc/rc.d/$daemon start
done

echo "Backlight to maximum"
echo 10 > /sys/devices/virtual/backlight/acpi_video0/brightness
sudo mount -a

}
