#!/bin/bash
#if [[ -z $DISPLAY ]];then
#    mpc pause 2>/dev/null
#    /usr/bin/mplayer -vo fbdev  "$@"
#    exit
#fi
$LOCK/mplayer /usr/bin/mplayer -slave -idle -input file=$MPSOCKET &>/dev/null  & 

if [ -z "$1" ];then
	FILE=`tail -1 ~/.mplayer.hist`
else
	prefix="`pwd`/"
    if [[ "$@" =~ ^/.* ]];then prefix=;fi
	FILE="${prefix}$@"
fi

echo "$FILE" >> $HOME/.mplayer.hist
mpc pause &>/dev/null
echo "loadfile \"$FILE\"" > $MPSOCKET
