#!/bin/bash
#if [[ -z $DISPLAY ]];then
#    mpc pause 2>/dev/null
#    /usr/bin/mplayer -vo fbdev  "$@"
#    exit
#fi
#set -x
HIST="$HOME/.mplayer.hist"
unset LD_PRELOAD
$LOCK/mplayer /usr/bin/mplayer -geometry 100% -identify -quiet -slave -idle -input file=$MPSOCKET &>>/tmp/mplayer.log  &

if [[ -z "$1" ]];then
      fnum=$(awk '{ print NR" "$0 }' $HIST | cut -d ":" -f 1 | uniq -f 1 | tac | $DMENU)
       #source ~/.zsh/.zsh_functions
       #fnum=$(dfilter "cat $HIST | tac")
       #echo "$fnum"
       #exit
      if [[ -z "$fnum" ]];then
          FILE=$(tail -1 $HIST | cut -d ":" -f 1)
      else
          num=`echo $fnum | cut -d " " -f 1`
          FILE=$(head -${num} $HIST | tail -1 | cut -d ":" -f 1)
      fi
      if [[ $fnum =~ .*:$ ]];then
          POSITION=$(grep $(cut -d " " -f 1 <<< $FILE) $HIST | tail -1 | cut -d ":" -f 2)
      fi
else
	prefix="`pwd`/"
    if [[ "$@" =~ ^/.* ]];then prefix=;fi
	FILE="${prefix}$@"
fi

#echo "$FILE" >> $HOME/.mplayer.hist

mpc pause &>/dev/null
echo "loadfile \"$FILE\"" > $MPSOCKET
echo "set_property time_pos $POSITION" > $MPSOCKET 
#set +x
