#!/bin/zsh

xnotify(){
    heading="$1"
    shift
    rest="$@"
    /usr/bin/notify-send  -u critical $heading "$rest"
}

cnotify(){
muxSend a "echo $@"
}

type=xnotify
pidof X &>/dev/null || type=cnotify

echo -e "\n\n$(date '+%F %H:%M') ==> $@\n\n" >> ~/.notify-history

case $1 in
    *rtorrent*)
      $type "Torrent download" "$2 download complete!"
      ;;
      *aria2c*)
        message=$(grep $2 $HOME/.download_history | tail -1 | cut -d "=" -f 1)
        $type "aria2c:" "$message download complete"
        ;;
     *) $type "Message:" "$@"
esac
