#!/bin/zsh
tasks="$(/bin/ls -A ~/.tasks/*.remain 2>/dev/null | wc -l)"
cookie="$(fortune -c  -a -s matrix archlinux debian goedel literature tbbt perl startrek the-godfather science linux linuxcookie wisdom)"
notify-send "Tasks left: <b>$tasks</b>
Time now is <i>$(date -R)</i>
----------------------
$cookie"
#sleep 2
mtasks="
"
counter=1

if [[ $tasks > 0 ]];then
    for t in ~/.tasks/*.remain;do
        mtasks="$mtasks
        Task#$counter: ${t:r:t}
        $(cat $t)
        "
        counter=$(($counter+1))
        if [[ $counter > 4 ]];then break;fi
    done
fi
~/bin/notify-send "$mtasks"

